# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apis.grpc import apis_pb2 as apis_dot_grpc_dot_apis__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ActionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/wowai.apis.ActionController/Create',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/wowai.apis.ActionController/Destroy',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/wowai.apis.ActionController/List',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionListRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.ActionListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/wowai.apis.ActionController/PartialUpdate',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionPartialUpdateRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/wowai.apis.ActionController/Retrieve',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionRetrieveRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/wowai.apis.ActionController/Update',
                request_serializer=apis_dot_grpc_dot_apis__pb2.ActionRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
                )


class ActionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionListRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.ActionListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionPartialUpdateRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionRetrieveRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.ActionRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wowai.apis.ActionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/Create',
            apis_dot_grpc_dot_apis__pb2.ActionRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/Destroy',
            apis_dot_grpc_dot_apis__pb2.ActionDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/List',
            apis_dot_grpc_dot_apis__pb2.ActionListRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.ActionListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/PartialUpdate',
            apis_dot_grpc_dot_apis__pb2.ActionPartialUpdateRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/Retrieve',
            apis_dot_grpc_dot_apis__pb2.ActionRetrieveRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.ActionController/Update',
            apis_dot_grpc_dot_apis__pb2.ActionRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AuthenControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/wowai.apis.AuthenController/Create',
                request_serializer=apis_dot_grpc_dot_apis__pb2.AuthRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.AuthResponse.FromString,
                )


class AuthenControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.AuthRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wowai.apis.AuthenController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthenController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.AuthenController/Create',
            apis_dot_grpc_dot_apis__pb2.AuthRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CustomUserControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/wowai.apis.CustomUserController/Create',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/wowai.apis.CustomUserController/Destroy',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/wowai.apis.CustomUserController/List',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserListRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/wowai.apis.CustomUserController/PartialUpdate',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserPartialUpdateRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/wowai.apis.CustomUserController/Retrieve',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserRetrieveRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/wowai.apis.CustomUserController/Update',
                request_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserRequest.SerializeToString,
                response_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
                )


class CustomUserControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomUserControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserListRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserPartialUpdateRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserRetrieveRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=apis_dot_grpc_dot_apis__pb2.CustomUserRequest.FromString,
                    response_serializer=apis_dot_grpc_dot_apis__pb2.CustomUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wowai.apis.CustomUserController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomUserController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/Create',
            apis_dot_grpc_dot_apis__pb2.CustomUserRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/Destroy',
            apis_dot_grpc_dot_apis__pb2.CustomUserDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/List',
            apis_dot_grpc_dot_apis__pb2.CustomUserListRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.CustomUserListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/PartialUpdate',
            apis_dot_grpc_dot_apis__pb2.CustomUserPartialUpdateRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/Retrieve',
            apis_dot_grpc_dot_apis__pb2.CustomUserRetrieveRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wowai.apis.CustomUserController/Update',
            apis_dot_grpc_dot_apis__pb2.CustomUserRequest.SerializeToString,
            apis_dot_grpc_dot_apis__pb2.CustomUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
